### PR TITLE
Python 3 porting changes:

### PR DESCRIPTION
**Pull request by jessp01**
1. use '()' when calling print - will also work with Python2. On 3, if
   not specified, will result in syntax err.
2. use Exception as e: instead of Exception, e: - This form is also
   backwards-compatible with 2.6 and 2.7.

Changes that are not backwards compat:
1. httplib is now called http.client
2. urllib2 now called urllib.request
   4.
   isinstance(myvalue, six.string_types)       # replacement for basestring
   isinstance(myvalue, six.text_type)          # replacement for unicode

### CODE REVIEW

**Comment by jessp01** [comment]
Note that this only gets the server up.
When trying to get to /config_home it just redirects back to login...

**Comment by hashimmm** [comment]
Thanks for the help. I'll look into it.

**Comment by jessp01** [comment]
Hello @hashimmm, are you sure you want to merge it to master though? some changes will work correctly with Python 2 as well but some, such as the module name changes, will not.

**Comment by hashimmm** [comment]
I made some more changes to make KTS work with Python 3.4 and to keep working with Python 2.7 as well, not just the ones in this pull request.

**Comment by jessp01** [comment]
Ah, great:) I will check it shortly.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by jessp01** [comment]
Just to confirm - tested against Python 3.4.0 and it worked well.

**Comment by hashimmm** [comment]
Thanks :)

**Pull request merged**
